### ISSUE TITLE
Part03: Ctrl+D not working to terminate list reading on Windows

### ISSUE THREAD

**Issue by redtrumpet** [RalfJung/rust-101#1]
Using the command prompt from Win7 and even the git bash I was not able to use Ctrl+D to finish the list input. Works on Linux. Maybe this is some rust issue?

**Comment by RalfJung** [comment]
This sounds like an issue with the shell, not with Rust. Do you know
what is the usual way on Windows to send an "EOF"? I am expecting a
reasonable shell here, there's not much I can do about buggy shells.

**Comment by RalfJung** [comment]
The interwebs say that on Windows, EOF is triggered by Ctrl-Z. So I'm adding that. Please let me know whether it works.
