### ISSUE TITLE
inc_print_even function name is misleading

### ISSUE THREAD

**Issue by link2xt** [RalfJung/rust-101#17]
Function [inc_print_even](https://github.com/RalfJung/rust-101/blob/fd7c4d96a0cd1c9882f790a2aad2c3bad1706082/src/part10.rs#L111) has nothing to do with even numbers. From its name I expected it to print even numbers. Maybe rename inc_print_even to inc_print_threshold?

**Comment by RalfJung** [comment]
Yeah, that'd make more sense... I guess I changed the function body without adapting the name. Good catch!
