### ISSUE TITLE
Inconsistencies in Part02

### ISSUE THREAD

**Issue by tjwelde** [RalfJung/rust-101#30]
First of all: Love this tutorial so far. Really on point and clears up questions I had when starting to get serious with Rust.

Two things I found, which seem to be wrong in this line: https://github.com/RalfJung/rust-101/blob/801f2b59728fba1e13d3e34a08457b812f8c0f56/src/part02.rs#L80

We didn't use `std::cmp::min(n, e)` in the previous part, just our own `min_i32(n, e)`: 
https://github.com/RalfJung/rust-101/blob/801f2b59728fba1e13d3e34a08457b812f8c0f56/src/part01.rs#L61

and

Rust automatically figures out, that **e** is of type `T`, not **n**.

Thank you for your work

**Comment by RalfJung** [comment]
Thanks!  Fixed.
