### ISSUE TITLE
Exercise 03.1 unclear (update needed?)

### ISSUE THREAD

**Issue by grothesque** [RalfJung/rust-101#37]
Thanks for this useful tutorial!

Exercise 03.1 asks to
> Define a trait Print to write a generic version of SomethingOrNothing::print. Implement that trait for i32, and change the code above to use it. I will again provide a skeleton for this solution.

The provided skeleton is:
```rust
pub trait Print {
    /* Add things here */
}
impl<T: Print> SomethingOrNothing<T> {
    fn print2(self) {
        unimplemented!()
    }
}
```

A possible working solution (with rustc 1.66) is
```rust
pub trait Print {
    fn print2(self);
}

impl Print for SomethingOrNothing<i32> {
    fn print2(self) {
        print!("The item is: ");
        match self {
            Nothing => println!("<nothing>"),
            Something::<i32>(n) => println!("{}", n),
        };
    }
}
```

However note that this does not correspond to filling out the provided skeleton!

The skeleton seems to aim at implementing a generic `print2` function (but I find that this is not clear from the text), for example as follows:

```rust
pub trait Print {
    fn print2(self);
}

impl<T: std::fmt::Display> Print for SomethingOrNothing<T> {
    fn print2(self) {
        print!("The item is: ");
        match self {
            Nothing => println!("<nothing>"),
            Something::<T>(n) => println!("{}", n),
        };
    }
}
```

However, this solution is crucially different from the skeleton as well, particularly in the `impl`-line.

Overall, I find this exercise in its current form confusing.  Is there a valid solution that can be reached by filling out the skeleton as compared to modifying it?

**Comment by RalfJung** [comment]
Thanks for the feedback @grothesque!

I have slightly expanded the exercise description and the template. Does that help?

**Comment by grothesque** [comment]
Thanks for acting on my feedback!

I now understand what you mean, and for a Rust newbie like me it's interesting that `print2` can be implemented in four ways: generic/concrete method on a trait/struct without changing the way in which it is used.

However, I still find the exercise formulation confusing.  It says:

> Define a trait Print to write a generic version of SomethingOrNothing::print. Implement that trait for i32, (...)

I tend to understand this such that the generic version of `SomethingOrNothing::print` (with its match expression) is supposed to go into the trait implementation.

IMHO it would be clearer to write something like:

Create a trait `Print` that defines a (simplistic) generic print functionality and implement that trait for type `i32`.  Then, use that generic functionality to create a generic version of  `SomethingOrNothing::print` called `print2` in order to disambiguate from the `print` defined previously.

(Note: it took me a little while until I realized that the changes you speak about are not on github but on your personal git hosting.  It didn't help that I saw *some* recent changes on github.)

**Comment by RalfJung** [comment]
> (Note: it took me a little while until I realized that the changes you speak about are not on github but on your personal git hosting. It didn't help that I saw some recent changes on github.)

Ah, the syncing is broken again, dang... Github keeps disabling the keys for that when they are not used for a while, super annoying. :/

**Comment by RalfJung** [comment]
All right, I think this is resolved by https://github.com/RalfJung/rust-101/commit/4cac8138d63e49c60d101bee79b9e60644b3de0a. Thanks for the feedback!
